#coding=utf-8

def do():
    print(u'进度：正常；时间百分比:1%；任务百分比1%；效果百分比：30%')
    print(u'时间： 当前时间：2020-08-29；出发时间, 2020-08-29；剩余时间：1000天；进度百分比:1%')
    print(u'任务： 总体任务：   ；完成任务：   ；剩余任务：   ')
    print('任务-时间 总表：')
    print('\n')
    print('\n')
    print('\n')
    print('学科-竞赛 分表：')
    print('语文：')
    print('\n')
    print('\n')
    print('数学：')
    print('\n')
    print('\n')
    print('英语：')
    print('\n')
    print('\n')
    print('物理：')
    print('\n')
    print('\n')
    print('化学：')
    print('\n')
    print('\n')
    print('生物：')
    print('\n')
    print('\n')
    print('历史：')
    print('\n')
    print('\n')
    print('地理：')
    print('\n')
    print('\n')
    print('政治：')
    print('\n')
    print('\n')
    print('竞赛-数学：（可比赛）')
    print('\n')
    print('\n')
    print('竞赛-计算机：（兴趣选修）')
    print('\n')
    print('\n')
    print('竞赛-物理：（准比赛）')
    print('\n')
    print('\n')

if __name__ == '__main__':
    do()
